# Generated by Django 4.0.8 on 2023-02-14 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentemail',
            name='status',
            field=models.CharField(choices=[('US', 'Unsent'), ('OK', 'Success'), ('FL', 'Failure')], default='US', max_length=2),
        ),
    ]
