# Generated by Django 4.0.8 on 2023-02-23 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0003_emailtemplate_notification_event_digest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='status',
            field=models.CharField(choices=[('IA', 'Inactive'), ('AC', 'Active')], default='IA', max_length=2),
        ),
    ]
