# Generated by Django 4.0.8 on 2023-03-08 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_group_post_groupmembership_group_members_comment'),
        ('emails', '0005_emailsnippet'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailsnippet',
            name='purpose',
            field=models.CharField(choices=[('RE', 'Reply'), ('ED', 'Event Digest'), ('GD', 'Group Digest')], default='US', max_length=2),
        ),
        migrations.AlterField(
            model_name='emailsnippet',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snippets', to='forum.post'),
        ),
        migrations.AlterField(
            model_name='emailsnippet',
            name='status',
            field=models.CharField(choices=[('US', 'Unsent'), ('SE', 'Sent')], default='US', max_length=2),
        ),
    ]
