# Generated by Django 4.0.8 on 2023-03-08 14:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0002_group_post_groupmembership_group_members_comment'),
        ('emails', '0006_emailsnippet_purpose_alter_emailsnippet_source_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailCommentSnippet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_content', models.TextField()),
                ('rich_content', models.TextField()),
                ('status', models.CharField(choices=[('US', 'Unsent'), ('SE', 'Sent')], default='US', max_length=2)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snippets', to='forum.comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snippets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='EmailSnippet',
        ),
    ]
