# Generated by Django 4.0.8 on 2023-03-10 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0007_emailcommentsnippet_delete_emailsnippet'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendEmailCommentJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('CR', 'Created'), ('IP', 'In progress'), ('CO', 'Completed')], default='CR', max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='emailcommentsnippet',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='snippets', to='emails.sendemailcommentjob'),
        ),
    ]
