# Generated by Django 4.0.8 on 2023-03-10 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0008_sendemailcommentjob_emailcommentsnippet_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendemailcommentjob',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sendemailcommentjob',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
